In [3]:
import pandas as pd
data={
    "Date":["2025-11-23","2025-12-4","2026-01-17"]
}
result=pd.DataFrame(data)
print(result)

         Date
0  2025-11-23
1   2025-12-4
2  2026-01-17

In [5]:
import pandas as pd
data={
    "Date":["2025-11-23","2025-12-4","2026-01-17"]
}
result=pd.DataFrame(data)
result["Date"]=pd.to_datetime(result["Date"])
print(result)

        Date
0 2025-11-23
1 2025-12-04
2 2026-01-17

In [6]:
Favmovie={
    "Movie":["Fidaa","UBS","Pspk","Hi Nanna"]
}
result=pd.DataFrame(Favmovie)
print(result)
result.sample(3,random_state=1)

      Movie
0     Fidaa
1       UBS
2      Pspk
3  Hi Nanna

      Movie
3  Hi Nanna
2      Pspk
0     Fidaa

In [7]:
Favmovie={
    "Movie":["Fidaa","UBS","Pspk","Hi Nanna"]
}
result=pd.DataFrame(Favmovie)
print(result)
result.sample(2,random_state=1)

      Movie
0     Fidaa
1       UBS
2      Pspk
3  Hi Nanna

      Movie
3  Hi Nanna
2      Pspk

In [8]:
Favmovie={
    "Movie":["Fidaa","UBS","Pspk"]
}
result=pd.DataFrame(Favmovie)
print(result)
result.sample(2,random_state=0)

   Movie
0  Fidaa
1    UBS
2   Pspk

  Movie
2  Pspk
1   UBS

In [9]:
import pandas as pd
data={
    "Date":["2025-11-23","2025-12-4","2026-01-17"]
}
result=pd.DataFrame(data)
result["Date"]=pd.to_datetime(result["Date"])
print(result)
result["Date"].dt.month

        Date
0 2025-11-23
1 2025-12-04
2 2026-01-17

0    11
1    12
2     1
Name: Date, dtype: int32

In [10]:
import pandas as pd
data={
    "Date":["2025-11-23","2025-12-4","2026-01-17"]
}
result=pd.DataFrame(data)
result["Date"]=pd.to_datetime(result["Date"])
print(result)
result["Date"].dt.year

        Date
0 2025-11-23
1 2025-12-04
2 2026-01-17

0    2025
1    2025
2    2026
Name: Date, dtype: int32

In [11]:
Favmovie={
    "Movie":["Fidaa","UBS","Pspk"]
}
result=pd.DataFrame(Favmovie)
print(result)
result.sample(1)

   Movie
0  Fidaa
1    UBS
2   Pspk

  Movie
1   UBS

In [12]:
Favmovie={
    "Movie":["Fidaa","UBS","Pspk"]
}
result=pd.DataFrame(Favmovie)
print(result)

   Movie
0  Fidaa
1    UBS
2   Pspk

In [13]:
import pandas as pd
data={
    "Date":["2025-11-23","2025-12-4","2026-01-17"]
}
result=pd.DataFrame(data)
result["Date"]=pd.to_datetime(result["Date"])
print(result)
result["Date"].dt.day

        Date
0 2025-11-23
1 2025-12-04
2 2026-01-17

0    23
1     4
2    17
Name: Date, dtype: int32

In [14]:
import pandas as pd
data={
    "Date":["2025-11-23","2025-12-4","2026-01-17"]
}
result=pd.DataFrame(data)
result["Date"]=pd.to_datetime(result["Date"])
print(result)
pd.Timestamp.now()

        Date
0 2025-11-23
1 2025-12-04
2 2026-01-17

Timestamp('2026-06-18 16:23:13.960975')

In [15]:
import pandas as pd
data={
    "Date":["2025-11-23","2025-12-4","2026-01-17"]
}
result=pd.DataFrame(data)
result["Date"]=pd.to_datetime(result["Date"])
print(result)
result["Date"].dt.day_name()

        Date
0 2025-11-23
1 2025-12-04
2 2026-01-17

0      Sunday
1    Thursday
2    Saturday
Name: Date, dtype: object

In [16]:
from datetime import datetime
date1=datetime(2025,9,18)
date2=datetime(2023,5,27)
print(date2-date1)

-845 days, 0:00:00

In [18]:
from datetime import datetime
date1=datetime(2025,9,18)
date2=datetime(2023,5,27)
print(date1-date2)

845 days, 0:00:00